### ISSUE TITLE
jd-eclipse not working for any class file in Luna on Windows

### ISSUE THREAD

**Issue by vwegert** [java-decompiler/jd-eclipse#2]
I have installed jd-eclipse as described in the installation instructions here on Github. I have verified that the file associations are set so that .class files are opened with the JD Class File Viewer. While the editor tab displays the fashionable coffee pot icon, the editor itself simply displays the Eclipse default class file viewer. No error in the error log. I've tried to add the class file to the build path - didn't change anything. Is there anything else I could try?

**Comment by emmanue1** [comment]
It works for me on Luna.
Have you installed the last release or rebuild the plugin yourself ?
RC2 contains a bug fixed with a20f1191e2802d28b5f93e25902903e4fe04d3b2.

**Comment by sylafrs** [comment]
I've got the same issue. I'm trying to decompile unity3d jar "unity-classes.jar"
(to know if it conflicts with a framework we have)

**Comment by sylafrs** [comment]
I've just copied it into my workspace (closed in Eclipse, copy/paste, open in Eclipse).
Doesn't work too.

This is an Android project.

**Comment by dmak** [comment]
I have Luna SR 1 (v4.4.1) and JD-Eclipse v1.0.3 works just fine.

**Comment by davidmichaelkarr** [comment]
I'm on Luna (4.4.2) on Win7.  I installed from the 1.0.0-RC2 update site zip.

My test case is classes in package "groovy.transform", from the "groovy-all-2.3.10.jar" file in the Gradle 2.4 distribution.

I'm finding that of the 38 classes in this package, only the following refuse to be decompiled by the Eclipse plugin (they just show the default class viewer):

* AutoExternalize
* CompileDynamic
* ConditionalInterrupt
* TailRecursive
* ThreadInterrupt
* TimedInterrupt

When I run jd-gui (1.4.0), it has no complaints about any of these classes.

**Comment by dmak** [comment]
Actually I found a problem with Luna 4.4.2: when switching from Java perspective to Debug perspective, Eclipse shows genetic error dialog with title "Error Occurred" and in the log:
```
!ENTRY org.eclipse.ui.workbench 4 2 2015-08-24 16:49:10.236
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.SWT.error(SWT.java:4327)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:476)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:348)
	at org.eclipse.swt.widgets.Composite.getChildren(Composite.java:451)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.showBreadcrumb(JavaEditor.java:1992)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.handlePreferenceStoreChanged(JavaEditor.java:2904)
	at org.eclipse.ui.texteditor.AbstractTextEditor$PropertyChangeListener.propertyChange(AbstractTextEditor.java:715)
```
